// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqhT1ojDC86Pk7U0okV5xrmeWsuOgBPGE',
    appId: '1:617821772610:web:ace4bd24671b97df6a46db',
    messagingSenderId: '617821772610',
    projectId: 'keep-note-818d2',
    authDomain: 'keep-note-818d2.firebaseapp.com',
    storageBucket: 'keep-note-818d2.appspot.com',
    measurementId: 'G-D8J9BTR1CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5acvsuYp085IGGFxWiNE1WP1cLKqNxks',
    appId: '1:617821772610:android:5860cd39cb91a68a6a46db',
    messagingSenderId: '617821772610',
    projectId: 'keep-note-818d2',
    storageBucket: 'keep-note-818d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvymlrQOlSbYQvq--bw5AmVYHkoVIzJcY',
    appId: '1:617821772610:ios:129aee8d9dba93e46a46db',
    messagingSenderId: '617821772610',
    projectId: 'keep-note-818d2',
    storageBucket: 'keep-note-818d2.appspot.com',
    iosBundleId: 'com.example.keepnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvymlrQOlSbYQvq--bw5AmVYHkoVIzJcY',
    appId: '1:617821772610:ios:f724d89cc2f004c26a46db',
    messagingSenderId: '617821772610',
    projectId: 'keep-note-818d2',
    storageBucket: 'keep-note-818d2.appspot.com',
    iosBundleId: 'com.example.keepnote.RunnerTests',
  );
}
